[build-system]
requires = [
  "setuptools>=66.1.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "gurk"
version = "2.1.0"
description = "Contains anything related to setting up a new computer (desktop) system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "gurk-template-plugin",
  "click",
  "distro",
  "filelock",
  "networkx",
  "packaging",
  "platformdirs",
  "pydantic",
  "requests",
  "rich",
  "ruamel.yaml",
  "tomli_w",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: POSIX :: Linux",
  "Environment :: Console",
  "Topic :: System :: Installation/Setup",
  "Intended Audience :: End Users/Desktop",
]
authors = [
  { name = "Arturo J. Roberti", email = "arturo.roberti@outlook.com" },
]

[project.license]
file = "LICENSE"

[project.optional-dependencies]
dev = [
  "commentjson",
  "pytest",
]
gurk = [
  "packaging",
  "requests",
]

[project.scripts]
gurk = "gurk.main:main"

[project.urls]
Homepage = "https://github.com/ArturoRoberti/gurk"
Repository = "https://github.com/ArturoRoberti/gurk"
Issues = "https://github.com/ArturoRoberti/gurk/issues"
Documentation = "https://github.com/ArturoRoberti/gurk#readme"

[tool.pytest.ini_options]
pythonpath = [
  "src",
]
testpaths = [
  "tests",
]
addopts = [
  "--import-mode=importlib",
]

[tool.setuptools.package-data]
gurk = [
  "plugins/**",
  "plugin_helpers/**",
]

[tool.setuptools.packages.find]
where = [
  "src",
]
