from .common import PYTEST_PLUGIN_NAME, PYTEST_PLUGIN_PATH
from .example_plugin import EXAMPLE_PLUGIN_REMOTE, EXAMPLE_PLUGIN_VERSIONING

__all__ = [
    "EXAMPLE_PLUGIN_REMOTE",
    "EXAMPLE_PLUGIN_VERSIONING",
    "PYTEST_PLUGIN_NAME",
    "PYTEST_PLUGIN_PATH",
]
