from .common import PYTEST_PLUGIN_NAME, PYTEST_PLUGIN_PATH
from .template import TEMPLATE_PLUGIN_REMOTE, TEMPLATE_PLUGIN_VERSIONING

__all__ = [
    "PYTEST_PLUGIN_NAME",
    "PYTEST_PLUGIN_PATH",
    "TEMPLATE_PLUGIN_REMOTE",
    "TEMPLATE_PLUGIN_VERSIONING",
]
