# Copyright 2026 Arturo Roberti
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI (Workflow)

on:
  issues:
    types: [opened, edited, labeled, unlabeled, unassigned]
  pull_request:
    # synchronize is not functionally necessary, but required to trigger 'required status checks' on PR updates
    types: [opened, edited, labeled, unlabeled, unassigned, synchronize]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  # Assignee
  ci-wf-assignee:
    uses: ./.github/workflows/reusable-assignee.yml

  # Branch name (only for PRs)
  ci-wf-branch-name:
    needs: ci-wf-assignee
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reusable-branch-name.yml

  # Labels
  ci-wf-labels:
    needs: ci-wf-branch-name
    if: ${{ always() && needs.ci-wf-branch-name.result != 'failure' }}
    uses: ./.github/workflows/reusable-labels.yml
    with:
      required-labels: "developer,bug,enhancement,automated"
      auto-assign-labels: |
        {
          "dev/": "developer",
          "feature/": "enhancement",
          "fix/": "bug",
          "automated/": "automated"
        }

  # Final job to report overall CI status
  ci-wf-status:
    needs:
      - ci-wf-assignee
      - ci-wf-branch-name
      - ci-wf-labels
    if: always()
    uses: ./.github/workflows/reusable-check-results.yml
    with:
      results: |
        ${{ needs.ci-wf-assignee.result }}
        ${{ needs.ci-wf-branch-name.result }}
        ${{ needs.ci-wf-labels.result }}
