# Copyright 2026 Arturo Roberti
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  pull_request:
    branches:
    - main
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch: null

jobs:
  # Run pre-commit checks
  ci-pre-commit:
    uses: ./.github/workflows/reusable-pre-commit.yml
    secrets:
      PAT: ${{ secrets.COMMIT_TOKEN }}

  # Run pytest on affected tasks
  ci-pytests:
    needs: ci-pre-commit
    # Avoid double runs if pre-commit pushed changes
    if: ${{ needs.ci-pre-commit.outputs.HAS_PUSHED != 'true' }}
    uses: ./.github/workflows/reusable-pytests.yml

  # Final job to report overall CI status
  ci-status:
    needs:
      - ci-pre-commit
      - ci-pytests
    if: always()
    uses: ./.github/workflows/reusable-check-results.yml
    with:
      results: |
        ${{ needs.ci-pre-commit.result }}
        ${{ needs.ci-pytests.result }}
