# Copyright 2026 Arturo Roberti
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Task pytests

on:
  workflow_call: null

jobs:
  pytest-affected-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install package
        run: pipx install -e .[dev]

      - name: Check if only plugin library files changed
        id: check-changes
        run: |
          # Check changed files
          changed_files=$(git diff --name-only origin/main...HEAD)
          source_changed=false
          while IFS= read -r file; do
            if [[ -n "$file" && "$file" != src/gurk/lib/plugins/* ]]; then
              source_changed=true
              break
            fi
          done <<< "$changed_files"

          # Output
          n_changed_files=$(echo "$changed_files" | wc -l)
          echo -e "Changed files ($n_changed_files):\n$changed_files" | head -n 11
          if [ "$n_changed_files" -gt 10 ]; then
            echo "..."
          fi
          if [ "$source_changed" = false ]; then
            echo "Only plugin library files changed. Skipping integration tests."
          else
            echo "Changes include non-plugin files. Integration tests will run."
          fi

          # Save result
          echo "RUN_INTEGRATION_TESTS=$source_changed" >> "$GITHUB_OUTPUT"

      - name: Compute affected tasks, based on changed files
        run: |
          VENV_PYTHON=$(pipx environment --value PIPX_HOME)/venvs/gurk/bin/python
          $VENV_PYTHON .github/scripts/gurk_find_affected_tasks.py

      - name: Run pytest for affected tasks
        id: run-task-pytests
        run: |
          # Check affected tasks
          if [ -z "${AFFECTED_TASKS}" ]; then
            echo "No affected tasks. Skipping pytest."
            exit 0
          else
            echo "Running pytest for affected tasks: ${AFFECTED_TASKS}"
          fi

          # Create a mock askpass script (no password needed in GitHub Actions)
          askpass_path=$(mktemp --suffix=".sh")
          echo '#!/bin/sh' > "$askpass_path"
          echo 'echo ""' >> "$askpass_path"
          chmod +x "$askpass_path"
          export SUDO_ASKPASS="$askpass_path"

          # Run pytest for affected tasks
          gurk pytest -v tests/tasks/test_tasks.py --maxfail=3 --tasks="${AFFECTED_TASKS}"

      - name: Run integration pytests
        if: ${{ steps.run-task-pytests.result != 'failure' && steps.check-changes.outputs.RUN_INTEGRATION_TESTS == 'true' }}
        run: |
          echo "pip: $(pip --version)"
          echo "python: $(python --version)"
          echo "pip3: $(pip3 --version)"
          gurk pytest -v tests/integration --maxfail=3
