# Copyright 2026 Arturo Roberti
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Daily Update Plugin Versions

# Run daily at 00:00 UTC
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-plugin-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install package
        run: pipx install .[dev]

      - name: Update plugin versions, if possible
        run: |
          VENV_PYTHON=$(pipx environment --value PIPX_HOME)/venvs/gurk/bin/python
          $VENV_PYTHON .github/scripts/gurk_update_plugins.py

      - name: Commit changes (if any)
        id: commit
        run: |
            # Commit any changes made by the update (if any)
            if [ -n "$(git status --porcelain)" ]; then
              git add -A
              git commit -m "Automated update of plugin versions" || echo "No commit created"
              echo "UPDATED=true" >> $GITHUB_ENV
            else
              echo "No changes to commit"
              echo "UPDATED=false" >> $GITHUB_ENV
            fi

      - name: Create pull request
        if: steps.commit.outputs.UPDATED == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
          commit-message: "Automated update of plugin versions"
          committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: automated/daily-check-${{ github.run_id }}
          delete-branch: true
          title: "Automated update of plugin versions"
          body: |
            This PR was automatically generated by a daily GitHub Actions workflow.
            It contains changes produced by `.github/scripts/gurk_update_plugins.py`.
          labels: automated
          assignees: ArturoRoberti
          reviewers: ArturoRoberti
